// frontend/src/pages/login.vue
<script setup lang="ts">
import { ref } from 'vue'

const nameOrEmail = ref('')
const password = ref('')

const handleSubmit = () => {
    console.log(nameOrEmail.value, password.value)
}
</script>

<template>
  <div class="flex items-center justify-center min-h-screen bg-gradient-to-br from-blue-100 to-indigo-200">
    <!-- 返回首页按钮 -->
    <a href="/" class="fixed top-6 left-6 z-50 bg-white/80 hover:bg-indigo-100 text-indigo-500 font-bold px-4 py-2 rounded-full shadow transition-all border border-indigo-200 flex items-center gap-1">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2.2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg>
      返回首页
    </a>
    <div class="bg-white shadow-xl rounded-3xl px-10 py-12 w-full max-w-md relative">
      <!-- Logo & Title -->
      <div class="flex flex-col items-center mb-8">
        <div class="w-14 h-14 rounded-full bg-indigo-100 flex items-center justify-center mb-3 shadow">
          <svg class="w-8 h-8 text-indigo-500" fill="none" stroke="currentColor" stroke-width="2.2" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round"
              d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M4 19.5V6.5A2.5 2.5 0 0 1 6.5 4h11A2.5 2.5 0 0 1 20 6.5v10.5M4 19.5h16" />
          </svg>
        </div>
        <h1 class="text-3xl font-extrabold text-indigo-700 tracking-wide mb-1">悦读图书馆</h1>
        <h2 class="text-lg text-indigo-500 font-medium">欢迎回来，开启你的阅读之旅！</h2>
      </div>
      <!-- Login Form -->
      <form @submit.prevent="handleSubmit" class="flex flex-col gap-6">
        <div>
          <label class="block mb-2 text-gray-700 font-semibold" for="nameOrEmail">用户名或邮箱</label>
          <div class="relative">
            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-indigo-400">
              <svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0zm2 6a6 6 0 1 0-12 0h12z" />
              </svg>
            </span>
            <input
              id="nameOrEmail"
              v-model="nameOrEmail"
              type="text"
              required
              placeholder="请输入用户名或邮箱"
              minlength="8"
              pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
              title="不少于8位，包含数字、小写字母、大写字母"
              class="pl-10 pr-4 py-3 w-full rounded-xl border border-gray-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition bg-gray-50 outline-none text-gray-700 placeholder-gray-400 shadow-sm"
            />
          </div>
          <p class="text-xs text-gray-400 mt-1 pl-1">
            不少于8位，包含数字、小写字母、大写字母
          </p>
        </div>
        <div>
          <label class="block mb-2 text-gray-700 font-semibold" for="password">密码</label>
          <div class="relative">
            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-indigo-400">
              <svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M12 15v2m-6 4h12a2 2 0 0 0 2-2v-6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2zm6-10V7a4 4 0 1 0-8 0v2" />
              </svg>
            </span>
            <input
              id="password"
              v-model="password"
              type="password"
              required
              placeholder="请输入密码"
              minlength="8"
              pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
              title="不少于8位，包含数字、小写字母、大写字母"
              class="pl-10 pr-4 py-3 w-full rounded-xl border border-gray-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition bg-gray-50 outline-none text-gray-700 placeholder-gray-400 shadow-sm"
            />
          </div>
          <p class="text-xs text-gray-400 mt-1 pl-1">
            不少于8位，包含数字、小写字母、大写字母
          </p>
        </div>
        <button
          class="w-full py-3 mt-2 text-lg font-bold rounded-xl bg-indigo-500 text-white shadow-md hover:bg-indigo-600 transition active:scale-95"
        >
          登录
        </button>
      </form>
      <!-- Register Link -->
      <div class="mt-8 text-center">
        <span class="text-gray-500 text-sm">还没有账号？</span>
        <a href="/register" class="text-indigo-600 hover:underline font-medium ml-1 transition-colors">去注册</a>
      </div>
    </div>
  </div>
</template>

// libraryy-web/src/app/(without_topbar)/login/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';

export default function LoginPage() {
  const [formData, setFormData] = useState({
    account: '',
    password: ''
  });

  const [showPassword, setShowPassword] = useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // 这里添加登录逻辑
    console.log('登录数据:', formData);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Logo 和标题 */}
        <div className="text-center mb-8">
          <div className="flex justify-center mb-4">
            <div className="w-16 h-16 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg">
              <Image 
                src="/logo.png" 
                alt="悦读图书馆" 
                width={40} 
                height={40}
                className="rounded-lg"
              />
            </div>
          </div>
          <h1 className="text-3xl font-bold text-gray-800 mb-2">悦读图书馆</h1>
          <p className="text-gray-600">欢迎回来，开始您的阅读之旅</p>
        </div>

        {/* 登录表单 */}
        <div className="bg-white rounded-2xl shadow-xl p-8 border border-gray-100">
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* 账号输入 */}
            <div>
              <label htmlFor="account" className="block text-sm font-medium text-gray-700 mb-2">
                账号
              </label>
              <div className="relative">
                <input
                  type="text"
                  id="account"
                  name="account"
                  value={formData.account}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors duration-200 bg-gray-50 focus:bg-white"
                  placeholder="请输入用户名或邮箱"
                  required
                />
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center">
                  <svg className="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                  </svg>
                </div>
              </div>
            </div>

            {/* 密码输入 */}
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
                密码
              </label>
              <div className="relative">
                <input
                  type={showPassword ? 'text' : 'password'}
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-colors duration-200 bg-gray-50 focus:bg-white pr-12"
                  placeholder="请输入密码"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                >
                  {showPassword ? (
                    <svg className="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L3 3m6.878 6.878L21 21" />
                    </svg>
                  ) : (
                    <svg className="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                  )}
                </button>
              </div>
            </div>

            {/* 记住我和忘记密码 */}
            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <input
                  id="remember-me"
                  name="remember-me"
                  type="checkbox"
                  className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                />
                <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-700">
                  记住我
                </label>
              </div>
              <div className="text-sm">
                <a href="#" className="font-medium text-blue-600 hover:text-blue-500 transition-colors duration-200">
                  忘记密码？
                </a>
              </div>
            </div>

            {/* 登录按钮 */}
            <button
              type="submit"
              className="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-4 rounded-lg font-medium hover:from-blue-700 hover:to-purple-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transform hover:scale-[1.02] transition-all duration-200 shadow-lg"
            >
              登录
            </button>
          </form>

          {/* 分割线 */}
          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-300" />
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-white text-gray-500">或</span>
              </div>
            </div>
          </div>

          {/* 注册链接 */}
          <div className="mt-6 text-center">
            <p className="text-sm text-gray-600">
              还没有账号？{' '}
              <Link 
                href="/register" 
                className="font-medium text-blue-600 hover:text-blue-500 transition-colors duration-200"
              >
                立即注册
              </Link>
            </p>
          </div>
        </div>

        {/* 底部信息 */}
        <div className="mt-8 text-center">
          <p className="text-xs text-gray-500">
            © 2024 悦读图书馆. 让阅读成为一种享受
          </p>
        </div>
      </div>
    </div>
  );
}
